Bump MSRV to 1.60
Fixes the build error due to log 0.4.21 requiring a newer version:

    error: package `log v0.4.21` cannot be built because it requires rustc 1.60.0 or newer, while the currently active rustc version is 1.56.1